modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="fantastical_fruits"
version="0.0.1"
displayName="Fantastical Fruits"
credits="Nehp, Fruitologist,"
displayURL="https://mcreator.net"
authors="Toasted Mahogany Studios"
description='''
A Nature Mod.
'''

[[dependencies.fantastical_fruits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




